#!/usr/bin/env python3
"""Writes shared/src/guild-decor-catalog.ts from mac/tools/guild_decor_catalog.json (make_guild_decor.py's catalog), and the
same list as mac/Resources/Guild/decor.json for the Mac's own hall (GuildArt.swift).

Every decoration also gets the guild level that unlocks it (GUILD.md §4.2): the catalog entry's "level", or 1 when it has
none (2026-10-08: everything made so far is open from the start; the next batches will say their level).

    python3 mac/tools/write_guild_decor_catalog.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOG = os.path.join(HERE, "guild_decor_catalog.json")
OUT = os.path.join(HERE, "..", "..", "shared", "src", "guild-decor-catalog.ts")
MAC_OUT = os.path.join(HERE, "..", "Resources", "Guild", "decor.json")
TOP_LEVEL = 7

items = json.load(open(CATALOG, encoding="utf-8"))
level = {item["id"]: int(item.get("level", 1)) for item in items}
assert all(1 <= v <= TOP_LEVEL for v in level.values()), "a level is out of 1–7"

rows = []
mac = {}
for item in items:
    seat = item.get("seat")
    row = {
        "id": item["id"],
        "name": item["name"],
        "category": item["category"],
        "race": item.get("race"),
        "size": item["size"],
        "level": level[item["id"]],
        "file": item["file"],
        "w": item["w"],
        "h": item["h"],
        "frames": item.get("frames", 1),
        "fps": item.get("fps", 0),
        "wall": bool(item.get("wall")),
        "flat": bool(item.get("flat")),
        "ceiling": bool(item.get("ceiling")),
        "seat": {"x": seat["x"], "y": seat["y"], "facing": seat.get("facing", "front")} if seat else None,
    }
    rows.append("  " + json.dumps(row, ensure_ascii=False))
    mac[row["id"]] = row

ts = """// Generated by mac/tools/write_guild_decor_catalog.py from mac/tools/guild_decor_catalog.json: do not edit by hand.
export interface GuildDecorKind {
  id: string;
  name: string;
  category: string;
  /** null: everyone's (公會共用); else the race whose member unlocks it. */
  race: string | null;
  /** Decoration room it takes: 1, 2 or 4. */
  size: number;
  /** The guild level that unlocks it. */
  level: number;
  /** Under mac/Resources/Guild (public/guild-hall on the phone): a strip of `frames` frames, each w × h, standing on its bottom middle. */
  file: string;
  w: number;
  h: number;
  frames: number;
  fps: number;
  /** Hangs on the back wall; lies flat on the floor (under everything); hangs from the ceiling (over everything). */
  wall: boolean;
  flat: boolean;
  ceiling: boolean;
  /** Where a sitter's feet go (sprite px), for things to sit on. */
  seat: { x: number; y: number; facing: string } | null;
}

export const GUILD_DECOR: readonly GuildDecorKind[] = [
""" + ",\n".join(rows) + "\n];\n"
open(OUT, "w", encoding="utf-8").write(ts)
with open(MAC_OUT, "w", encoding="utf-8") as f:
    json.dump(mac, f, ensure_ascii=False, separators=(",", ":"))
print(f"{len(rows)} decorations → {os.path.relpath(OUT)}")
