#!/usr/bin/env python3
"""Writes shared/src/guild-decor-catalog.ts from mac/tools/guild_decor_catalog.json (make_guild_decor.py's catalog), and the
same list as mac/Resources/Guild/decor.json for the Mac's own hall (GuildArt.swift).

Every decoration also gets the guild level that unlocks it (GUILD.md §4.2): the catalog entry's "level", or 1 when it has
none (2026-10-08: everything made so far is open from the start; the next batches will say their level).

    python3 mac/tools/write_guild_decor_catalog.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOG = os.path.join(HERE, "guild_decor_catalog.json")
OUT = os.path.join(HERE, "..", "..", "shared", "src", "guild-decor-catalog.ts")
MAC_OUT = os.path.join(HERE, "..", "Resources", "Guild", "decor.json")
TOP_LEVEL = 7

# The pieces a new guild starts with that were the hall's own furniture before (mac/Resources/Guild/furniture), so they can be
# moved and taken away like any other (2026-10-08 使用者：「所有的東西都應該要能移除或是放置」).
EXTRAS = [
    {"id": "guild_desk", "name": "公會辦公桌", "category": "辦公桌椅", "size": 2, "w": 40, "h": 22, "frames": 2, "fps": 3, "file": "furniture/desk.png"},
    {"id": "fireplace", "name": "壁爐", "category": "燈具", "size": 4, "w": 48, "h": 40, "frames": 3, "fps": 6, "file": "furniture/fireplace.png"},
    {"id": "water_elemental", "name": "水精靈飲水台", "category": "廚房飲料", "size": 1, "w": 16, "h": 24, "frames": 3, "fps": 3, "file": "furniture/water_dispenser.png"},
]
# Desks one works at (sitting behind), and the water one drinks beside (shared/src/guild-hall.ts hallFurnishing).
DESKS = {"guild_desk", "crystal_desk", "oak_desk", "corner_desk", "guildmaster_desk", "drafting_table", "gob_log_desk", "elf_root_desk", "und_coffin_desk",
         "l2_writing_desk", "l3_secretary_desk", "l6_commander_desk", "l7_archmage_desk"}
DRINKS = {"water_elemental", "water_cooler", "gob_waterskin", "elf_spring_basin", "l3_big_cooler", "l6_water_trough", "l7_elixir_fountain"}

items = json.load(open(CATALOG, encoding="utf-8")) + EXTRAS
level = {item["id"]: int(item.get("level", 1)) for item in items}
assert all(1 <= v <= TOP_LEVEL for v in level.values()), "a level is out of 1–7"
# A holiday piece names its season (shared/src/guild-seasons.ts GUILD_SEASONS): put down only while the season is on.
SEASONS = set(re.findall(r'\{ id: "([a-z_]+)", name: ', open(os.path.join(HERE, "..", "..", "shared", "src", "guild-seasons.ts"), encoding="utf-8").read()))
assert all(item.get("season") is None or item["season"] in SEASONS for item in items), "a piece names a season that does not exist"

rows = []
mac = {}
for item in items:
    seat = item.get("seat")
    row = {
        "id": item["id"],
        "name": item["name"],
        "category": item["category"],
        "race": item.get("race"),
        "size": item["size"],
        "level": level[item["id"]],
        "season": item.get("season"),
        "file": item["file"],
        "w": item["w"],
        "h": item["h"],
        "frames": item.get("frames", 1),
        "fps": item.get("fps", 0),
        "wall": bool(item.get("wall")),
        "flat": bool(item.get("flat")),
        "ceiling": bool(item.get("ceiling")),
        "seat": {"x": seat["x"], "y": seat["y"], "facing": seat.get("facing", "front")} if seat else None,
        "desk": item["id"] in DESKS,
        "drink": item["id"] in DRINKS,
        "living": item["category"] == "會動的",
    }
    rows.append("  " + json.dumps(row, ensure_ascii=False))
    mac[row["id"]] = row

ts = """// Generated by mac/tools/write_guild_decor_catalog.py from mac/tools/guild_decor_catalog.json: do not edit by hand.
export interface GuildDecorKind {
  id: string;
  name: string;
  category: string;
  /** null: everyone's (公會共用); else the race whose member unlocks it. */
  race: string | null;
  /** Decoration room it takes: 1, 2 or 4. */
  size: number;
  /** The guild level that unlocks it. */
  level: number;
  /** A holiday piece: the season (shared/src/guild-seasons.ts) it can be put down in; null: always. */
  season: string | null;
  /** Under mac/Resources/Guild (public/guild-hall on the phone): a strip of `frames` frames, each w × h, standing on its bottom middle. */
  file: string;
  w: number;
  h: number;
  frames: number;
  fps: number;
  /** Hangs on the back wall; lies flat on the floor (under everything); hangs from the ceiling (over everything). */
  wall: boolean;
  flat: boolean;
  ceiling: boolean;
  /** Where a sitter's feet go (sprite px), for things to sit on. */
  seat: { x: number; y: number; facing: string } | null;
  /** A desk one works at; water one drinks beside; one of the little living things (not in the way). */
  desk: boolean;
  drink: boolean;
  living: boolean;
}

export const GUILD_DECOR: readonly GuildDecorKind[] = [
""" + ",\n".join(rows) + "\n];\n"
open(OUT, "w", encoding="utf-8").write(ts)
with open(MAC_OUT, "w", encoding="utf-8") as f:
    json.dump(mac, f, ensure_ascii=False, separators=(",", ":"))
print(f"{len(rows)} decorations → {os.path.relpath(OUT)}")
